# Generated by Django 4.0.3 on 2022-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
                ('from_email', models.EmailField(max_length=254)),
                ('recipient_list', models.EmailField(max_length=254)),
            ],
        ),
    ]
