# Generated by Django 4.0.3 on 2022-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='recipient_list',
            new_name='receiver_one',
        ),
        migrations.AddField(
            model_name='emails',
            name='receiver_five',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='emails',
            name='receiver_four',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='emails',
            name='receiver_three',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='emails',
            name='receiver_two',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
